<a href="https://colab.research.google.com/github/IliyaShestakov/OOAP/blob/main/LAB1_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1.1
import numpy as np
n = int(input())
Z = np.zeros(n)
print(Z)

9
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 1.2
Z = np.zeros((10, 10), dtype = np.float64)
p = Z.itemsize
r = Z.size
print(p * r)

800


In [ ]:
Z = np.array([1, 2, 3], dtype = np.float64)
p = Z.itemsize
r = Z.size
print(p * r)

24


In [ ]:
# 1.3
n = int(input())
Z = np.zeros(n)
m = int(input())
Z[m] = 1
print(Z)

10
4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 1.4
n = int(input())
m = int(input())
Z = np.arange(n, m + 1)
print(Z)

10
50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# 1.5
Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
print(Z)

[4 3 2 1]


In [3]:
# 1.6
n = int(input())
m, k = map(int, input().split())
Z = np.arange(n).reshape(m,k)
print(Z)

6
2 3
[[0 1 2]
 [3 4 5]]


In [7]:
# 1.7
Z = np.array([1, 2, 0, 0, 4, 0])
NonZerros = np.nonzero(Z)
print(NonZerros)

(array([0, 1, 4]),)


In [ ]:
Z = np.array([1, 2, 0, 0, 4, 0])
NonZerros = np.nonzero(Z)
print(NonZerros)

(array([0, 1, 4]),)


In [ ]:
# 1.8
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 1.9
np.random.seed(42) 
n = int(input())
l = int(input())
m = int(input())
Z = np.random.random((n,l,m))
print(Z)

2
2
2
[[[0.37454012 0.95071431]
  [0.73199394 0.59865848]]

 [[0.15601864 0.15599452]
  [0.05808361 0.86617615]]]


In [ ]:
# 1.10
np.random.seed(42)
n = int(input())
m = int(input())
Z = np.random.random((n, m))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

10
10
0.005522117123602399 0.9868869366005173


In [ ]:
np.random.seed(42)
n = int(input())
m = int(input())
Z = np.random.random((n, m))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

2
6
0.020584494295802447 0.9699098521619943


In [ ]:
# 1.11
np.random.seed(42)
n = int(input())
m = int(input())
Z = np.random.random((n,m))
c = Z.mean()
print(c)

30
30
0.4923750160905882


In [ ]:
np.random.seed(42)
n = int(input())
m = int(input())
Z = np.random.random((n,m))
c = Z.mean()
print(c)

12
6
0.46798212705144554


In [ ]:
# 1.12
A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])
Z = np.dot(A, B)
print(Z)

39.5


In [ ]:
A = np.array([1, 3, 5, 7, 9])
B = np.array([-2, 4, -6, 8, -10])
Z = np.dot(A, B)
print(Z)

-54


In [ ]:
# 1.13
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5],
 [12.5],
 [13.5]
])
rows1, columns1 = A.shape
rows2, columns2 = B.shape
if columns1 == rows2:
    Z = np.dot(A, B)
    print(Z) 
else:
    Z = "Упс! Что-то пошло не так..."
    print(Z)

[[ 77. ]
 [189.5]]


In [ ]:
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5, 12.5, 13.5]
])
rows1, columns1 = A.shape
rows2, columns2 = B.shape
if columns1 == rows2:
    Z = np.dot(A, B)
    print(Z) 
else:
    Z = "Упс! Что-то пошло не так..."
    print(Z)

Упс! Что-то пошло не так...


In [ ]:
# 1.14
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
Z = np.array([-10, -5, 0, 5, 10])
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[-10  -5   0  -5  10]


In [ ]:
# 1.15
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
np.prod(np.diag(X)[np.diag(X)!=0])


3

In [ ]:
# 1.16
n = int(input())
Z = np.full(n, 0)
print(Z)

5
[0 0 0 0 0]


In [ ]:
# 1.17
Z = np.zeros((10, 10))
print(Z.nbytes)

800


In [ ]:
Z = np.array([1,2,3], dtype=np.float64)
print(Z.nbytes)

24


In [ ]:
# 1.18
n = int(input())
Z = np.full(n, 0)
m = int(input())
Z[m] = 1
print(Z)

10
4
[0 0 0 0 1 0 0 0 0 0]


In [ ]:
# 1.19
x = int(input())
y = int(input())
Z = np.zeros(shape=y+1 - x, dtype=int)
for i in range(len(Z)):
    Z[i] = x
    x += 1
print(Z)

10
50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# 1.20

In [5]:
# 1.21
n = int(input())
m, l = tuple(map(int, input().split()))

Z = np.zeros((m, l), dtype = 'int')

for i in range(m):
    Z[i] = np.arange(l*i, l*(i+1))
print(Z)

6
2 3
[[0 1 2]
 [3 4 5]]


In [ ]:
# 1.22

In [ ]:
# 1.23
n = int(input())
Z = np.zeros(n * n)
Z[::n + 1] = 1
Z = Z.reshape([n, n])
print(Z)

In [ ]:
# 1.24

In [8]:
# 1.25
np.random.seed(42)
Z = np.random.rand(*map(int, input().split()))
print(np.amin(Z))
print(np.amax(Z))

10 10
0.005522117123602399
0.9868869366005173
